# Generated by Django 4.2.2 on 2023-07-04 04:02

import Accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('ENTC', 'Electronics and Telecommunication')], max_length=50)),
                ('roll_id', models.TextField(blank=True, null=True)),
                ('profile_pic', models.ImageField(upload_to=Accounts.models.user_directory_path_for_students)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('ENTC', 'Electronics and Telecommunication')], max_length=50)),
                ('profile_pic', models.ImageField(upload_to=Accounts.models.user_directory_path_for_faculty)),
                ('designation', models.CharField(max_length=200)),
                ('linkedin_url', models.URLField()),
                ('reasearch_gate_url', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('ENTC', 'Electronics and Telecommunication')], max_length=50)),
                ('roll_id', models.TextField(blank=True, null=True)),
                ('profile_pic', models.ImageField(upload_to=Accounts.models.user_directory_path_for_alumni)),
                ('github_url', models.URLField()),
                ('linkedin_url', models.URLField()),
                ('portfolio_url', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('ENTC', 'Electronics and Telecommunication')], max_length=50)),
                ('profile_pic', models.ImageField(upload_to=Accounts.models.user_directory_path_for_admin)),
                ('designation', models.CharField(max_length=200)),
                ('linkedin_url', models.URLField()),
                ('reasearch_gate_url', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
