# Generated by Django 4.2.2 on 2023-07-04 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('platform_title', models.CharField(max_length=200)),
                ('platform_link', models.URLField(max_length=500)),
                ('speaker', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField()),
                ('contact_to', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
